"""
HTML Report Renderer for Papertrail using html_utils.

This module provides the HypersonicReport class for generating styled HTML reports
from Papertrail Entry objects using the html_utils library.
"""

from pathlib import Path
from typing import List, Union
from tts_papertrail.base import (
    Report, Entry, TextEntry, ListEntry, TableEntry, PowerTableEntry,
    SectionEntry, SummaryTable, RichText, ListItem
)
from tts_html_utils.core.compiler import HtmlCompiler
from tts_html_utils.core.components.text import H1, H2, P, Span, Strong
from tts_html_utils.core.components.misc import HR
from tts_html_utils.core.components.table import PowerTable
from tts_html_utils.core.components.list import UL, LI
from tts_html_utils.core.components.base import HtmlComponentSimple
from tts_html_utils.core.components.structure import PaneContainer
from tts_data_utils.core.generic import GenericContainer


class HypersonicReport:
    """
    Renders a Papertrail report as an HTML file using html_utils components.
    
    Converts Papertrail Entry objects (TextEntry, ListEntry, TableEntry, etc.)
    into html_utils components for professional HTML output.
    
    Example:
        >>> report = HypersonicReport("Mission Report", "Ops Team")
        >>> report.add_entry(TextEntry("Summary", "All systems nominal"))
        >>> report.save("report.html")
    """
    
    def __init__(self, name: str, author: str, dark_mode: bool = False):
        """
        Initialize a Hypersonic HTML report.
        
        Args:
            name: The report title
            author: The author's name
            dark_mode: If True, uses dark theme styling (not yet implemented)
        """
        self.name = name
        self.author = author
        self.created_at = None  # Will be set by Report.to_html()
        self.entries = []
        self.dark_mode = dark_mode
        self.compiler = HtmlCompiler(name)
    
    def add_entry(self, entry: Entry):
        """Adds a content entry to the report."""
        self.entries.append(entry)

    def save(self, filename: str):
        """
        Saves the report as an HTML file.
        
        Args:
            filename: Output path (will append .html if not present)
        """
        if not filename.endswith('.html'):
            filename += '.html'
        
        # Build the report content
        self._build_report()
        
        # Render to file
        self.compiler.render_to_file(filename)
    
    def _build_report(self):
        """Build the HTML report using html_utils components with PaneContainer."""
        # Add title
        self.compiler.add_body_component(H1(self.name))
        
        # Add metadata
        meta_text = f"Author: {self.author} | Generated: {self.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}"
        self.compiler.add_body_component(P(meta_text, style={'color': '#6c757d', 'font-size': '0.9em', 'margin-bottom': '30px'}))
        
        self.compiler.add_body_component(HR())
        
        # Create PaneContainer for entries - each entry becomes a tab
        pane_container = PaneContainer()
        
        # Add each entry as a separate pane
        for entry in self.entries:
            # Create a temporary compiler for this pane's content
            pane_compiler = HtmlCompiler(entry.title or "Content")
            
            # Build the entry content into the pane compiler
            if isinstance(entry, SectionEntry):
                self._add_section_to_compiler(pane_compiler, entry)
            elif isinstance(entry, TextEntry):
                self._add_text_to_compiler(pane_compiler, entry)
            elif isinstance(entry, ListEntry):
                self._add_list_to_compiler(pane_compiler, entry)
            elif isinstance(entry, SummaryTable):
                self._add_summary_table_to_compiler(pane_compiler, entry)
            elif isinstance(entry, PowerTableEntry):
                self._add_power_table_to_compiler(pane_compiler, entry)
            elif isinstance(entry, TableEntry):
                self._add_table_to_compiler(pane_compiler, entry)
            
            # Add pane with the entry's title and content
            pane_container.add_pane(
                pane_compiler.body_components,
                entry.title or "Content"
            )
        
        # Add the pane container to the main report
        self.compiler.add_body_component(pane_container)
        
        # Add footer
        self.compiler.add_body_component(HR())
        self.compiler.add_body_component(P("Generated by Papertrail Hypersonic", 
                                           style={'text-align': 'center', 'color': '#6c757d', 'margin-top': '40px'}))
    
    # Methods for rendering entries to a specific compiler (for panes)
    def _add_section_to_compiler(self, compiler: HtmlCompiler, entry: SectionEntry):
        """Add a SectionEntry to a specific compiler."""
        for part in entry.parts:
            if isinstance(part, TextEntry):
                self._add_text_to_compiler(compiler, part)
            elif isinstance(part, ListEntry):
                self._add_list_to_compiler(compiler, part)
            elif isinstance(part, PowerTableEntry):
                self._add_power_table_to_compiler(compiler, part)
            elif isinstance(part, TableEntry):
                self._add_table_to_compiler(compiler, part)
    
    def _add_text_to_compiler(self, compiler: HtmlCompiler, entry: TextEntry):
        """Add a TextEntry to a specific compiler."""
        for item in entry.content:
            if isinstance(item, str):
                compiler.add_body_component(P(item))
            elif isinstance(item, RichText):
                compiler.add_body_component(P(self._richtext_to_span(item)))
    
    def _add_list_to_compiler(self, compiler: HtmlCompiler, entry: ListEntry):
        """Add a ListEntry to a specific compiler."""
        list_items = []
        for item in entry.items:
            content_parts = []
            for rt in item.content:
                if isinstance(rt, RichText):
                    content_parts.append(self._richtext_to_span(rt))
                else:
                    content_parts.append(str(rt))
            combined_content = content_parts[0] if len(content_parts) == 1 else content_parts
            list_items.append(combined_content)
        
        ul = UL()
        for item_content in list_items:
            ul.add_child(LI(item_content))
        compiler.add_body_component(ul)
    
    def _add_summary_table_to_compiler(self, compiler: HtmlCompiler, entry: SummaryTable):
        """Add a SummaryTable to a specific compiler."""
        table = GenericContainer(raw_data=entry.rows).power_table()
        compiler.add_body_component(table)
    
    def _add_power_table_to_compiler(self, compiler: HtmlCompiler, entry: PowerTableEntry):
        """Add a PowerTableEntry to a specific compiler."""
        container = entry.container.with_cols(entry.columns) if entry.columns else entry.container
        table = container.power_table(
            superheader=None,  # Title is in the pane tab
            add_filters=entry.add_filters,
            add_sorting=entry.add_sorting
        )
        compiler.add_body_component(table)
    
    def _add_table_to_compiler(self, compiler: HtmlCompiler, entry: TableEntry):
        """Add a TableEntry to a specific compiler using GenericContainer."""
        # Normalize data to list of dicts (for GenericContainer)
        raw_data = []
        
        # Determine headers: use provided headers or generate indices
        if entry.headers:
            headers = entry.headers
        else:
            # Generate dummy headers "0", "1", "2"... if missing
            max_cols = max((len(r) for r in entry.data), default=0)
            headers = [str(i) for i in range(max_cols)]

        for row in entry.data:
            row_dict = {}
            for i, cell in enumerate(row):
                # Extract text from RichText if present
                val = cell.text if isinstance(cell, RichText) else str(cell)
                
                # Map value to corresponding header
                if i < len(headers):
                    row_dict[headers[i]] = val
            raw_data.append(row_dict)
            
        # Create the table using GenericContainer, which handles PowerTable creation securely
        table = GenericContainer(raw_data=raw_data).power_table()
        compiler.add_body_component(table)
    
    # Legacy methods (for backward compatibility if needed)
    def _add_section_entry(self, entry: SectionEntry):
        """Add a SectionEntry (grouping of multiple entries)."""
        if entry.title:
            self.compiler.add_body_component(H2(entry.title, style={'border-left': '4px solid #007bff', 'padding-left': '15px'}))
        
        for part in entry.parts:
            if isinstance(part, TextEntry):
                self._add_text_entry(part, include_title=False)
            elif isinstance(part, ListEntry):
                self._add_list_entry(part, include_title=False)
            elif isinstance(part, PowerTableEntry):
                self._add_power_table_entry(part, include_title=False)
            elif isinstance(part, TableEntry):
                self._add_table_entry(part, include_title=False)
    
    def _add_text_entry(self, entry: TextEntry, include_title: bool = True):
        """Add a TextEntry."""
        if include_title and entry.title:
            self.compiler.add_body_component(H2(entry.title, style={'border-left': '4px solid #007bff', 'padding-left': '15px'}))
        
        for item in entry.content:
            if isinstance(item, str):
                self.compiler.add_body_component(P(item))
            elif isinstance(item, RichText):
                self.compiler.add_body_component(P(self._richtext_to_span(item)))
    
    def _add_list_entry(self, entry: ListEntry, include_title: bool = True):
        """Add a ListEntry."""
        if include_title and entry.title:
            self.compiler.add_body_component(H2(entry.title, style={'border-left': '4px solid #007bff', 'padding-left': '15px'}))
        
        # Build list items
        list_items = []
        for item in entry.items:
            content_parts = []
            for rt in item.content:
                if isinstance(rt, RichText):
                    content_parts.append(self._richtext_to_span(rt))
                else:
                    content_parts.append(str(rt))
            
            # Join content parts
            combined_content = content_parts[0] if len(content_parts) == 1 else content_parts
            list_items.append(combined_content)
        
        # Create UL component
        ul = UL()
        for item_content in list_items:
            ul.add_child(LI(item_content))
        
        self.compiler.add_body_component(ul)
    
    def _add_summary_table_entry(self, entry: SummaryTable, include_title: bool = True):
        """Add a SummaryTable as a simple PowerTable."""
        if include_title and entry.title:
            self.compiler.add_body_component(H2(entry.title, style={'border-left': '4px solid #007bff', 'padding-left': '15px'}))
        
        table = GenericContainer(raw_data=entry.rows).power_table()
        self.compiler.add_body_component(table)
    
    def _add_power_table_entry(self, entry: PowerTableEntry, include_title: bool = True):
        """Add a PowerTableEntry using DataContainer's power_table() method."""
        # Filter columns if specified
        container = entry.container.with_cols(entry.columns) if entry.columns else entry.container
        
        # Use the container's power_table method with filtering and sorting
        table = container.power_table(
            superheader=entry.title if include_title else None,
            add_filters=entry.add_filters,
            add_sorting=entry.add_sorting
        )
        
        self.compiler.add_body_component(table)
    
    def _add_table_entry(self, entry: TableEntry, include_title: bool = True):
        """Add a TableEntry using GenericContainer (legacy mode updated)."""
        # Build raw data for GenericContainer
        raw_data = []
        headers = entry.headers
        if not headers:
             max_cols = max((len(r) for r in entry.data), default=0)
             headers = [str(i) for i in range(max_cols)]
             
        for row in entry.data:
            row_dict = {}
            for i, cell in enumerate(row):
                val = cell.text if isinstance(cell, RichText) else str(cell)
                if i < len(headers):
                    row_dict[headers[i]] = val
            raw_data.append(row_dict)
            
        container = GenericContainer(raw_data=raw_data)
        table = container.power_table()
        
        if include_title and entry.title:
            table.add_superheader(entry.title)
            
        self.compiler.add_body_component(table)
    
    def _richtext_to_span(self, rt: RichText) -> Union[Span, Strong, str]:
        """Convert a RichText object to an html_utils Span component."""
        style = {}
        
        if rt.color:
            style['color'] = rt.color
        if rt.bg_color:
            style['background-color'] = rt.bg_color
        
        # If bold, use Strong tag
        if rt.bold:
            if rt.italic:
                style['font-style'] = 'italic'
            return Strong(rt.text, style=style)
        
        # If italic
        if rt.italic:
            style['font-style'] = 'italic'
        
        # If any styling, use Span
        if style or rt.url:
            # TODO: handle URL with link component when available
            return Span(rt.text, style=style)
        
        # Plain text
        return rt.text